//create datasctructure for product

export interface productData {
  name: string;
  original_price: number;
  discounted: number;
  price: number;
  case_size: string[];
  availability: string;
  gender: string;
  brands: string;
  buy_back_assurance: string;
  dial_colours: string[];
  watch_styles: string[];
  strap_bracelet_material: string;
  strap_colours: string[];
  movement_type: string;
  case_material: string;
  purchase_year: string;
  liked: boolean;
  relevance: number;
  best_seller: number;
  new_arrival: number;
  editor_top_picks: number;
}

export const ProductListData: productData[] = [
  {
    name: "Rolex Submariner",
    original_price: 200,
    discounted: 150,
    price: 150,
    case_size: ["17 - 19mm", "20 - 22mm"],
    availability: "Available",
    gender: "Men",
    brands: "Rolex",
    buy_back_assurance: "80%",
    dial_colours: ["Black", "Brown"],
    watch_styles: ["Vintage", "Sport"],
    strap_bracelet_material: "Leather",
    strap_colours: ["Black", "Brown"],
    movement_type: "Automatic",
    case_material: "Stainless Steel",
    purchase_year: "2012",
    liked: true,
    relevance: 5,
    best_seller: 5,
    new_arrival: 7,
    editor_top_picks: 3,
  },

  {
    name: "Apple Watch Series 6",
    original_price: 300,
    discounted: 250,
    price: 250,
    case_size: ["23 - 25mm", "26 - 28mm"],
    availability: "Available",
    gender: "Women",
    brands: "Apple",
    buy_back_assurance: "70%",
    dial_colours: ["Burgundy", "Red"],
    watch_styles: ["Dress", "Casual"],
    strap_bracelet_material: "Steel",
    strap_colours: ["Black", "Blue"],
    movement_type: "Quartz",
    case_material: "Silver",
    purchase_year: "2014",
    liked: false,
    relevance: 7,
    best_seller: 8,
    new_arrival: 2,
    editor_top_picks: 4,
  },

  {
    name: "Hugo Boss Men's Chronograph Watch",
    original_price: 1500,
    discounted: 1200,
    price: 1200,
    case_size: ["32 - 34mm", "35 - 37mm"],
    availability: "Sold",
    gender: "Unisex",
    brands: "Aspen",
    buy_back_assurance: "50%",
    dial_colours: ["Blue"],
    watch_styles: ["Diver"],
    strap_bracelet_material: "Rubber",
    strap_colours: ["Purple"],
    movement_type: "Manual",
    case_material: "Stainless Steel and Gold",
    purchase_year: "2016",
    liked: false,
    relevance: 3,
    best_seller: 9,
    new_arrival: 10,
    editor_top_picks: 1,
  },
  {
    name: "Rolex Datejust",
    original_price: 200,
    discounted: 150,
    price: 150,
    case_size: ["17 - 19mm", "20 - 22mm"],
    availability: "Available",
    gender: "Men",
    brands: "Rolex",
    buy_back_assurance: "60%",
    dial_colours: ["Black", "Brown"],
    watch_styles: ["Vintage", "Sport"],
    strap_bracelet_material: "Leather",
    strap_colours: ["Black", "Brown"],
    movement_type: "Automatic",
    case_material: "Stainless Steel",
    purchase_year: "2012",
    liked: true,
    relevance: 5,
    best_seller: 3,
    new_arrival: 6,
    editor_top_picks: 7,
  },
  {
    name: "Aspen Classic Aviator Watch",
    original_price: 300,
    discounted: 250,
    price: 250,
    case_size: ["23 - 25mm", "26 - 28mm"],
    availability: "Available",
    gender: "Women",
    brands: "Apple",
    buy_back_assurance: "70%",
    dial_colours: ["Burgundy", "Red"],
    watch_styles: ["Dress", "Casual"],
    strap_bracelet_material: "Steel",
    strap_colours: ["Black", "Blue"],
    movement_type: "Quartz",
    case_material: "Silver",
    purchase_year: "2014",
    liked: false,
    relevance: 7,
    best_seller: 2,
    new_arrival: 9,
    editor_top_picks: 5,
  },
  {
    name: "Hublot Big Bang",
    original_price: 1500,
    discounted: 1200,
    price: 1200,
    case_size: ["32 - 34mm", "35 - 37mm"],
    availability: "Sold",
    gender: "Unisex",
    brands: "Aspen",
    buy_back_assurance: "80%",
    dial_colours: ["Blue"],
    watch_styles: ["Diver"],
    strap_bracelet_material: "Rubber",
    strap_colours: ["Purple"],
    movement_type: "Manual",
    case_material: "Stainless Steel and Gold",
    purchase_year: "2016",
    liked: false,
    relevance: 3,
    best_seller: 1,
    new_arrival: 4,
    editor_top_picks: 6,
  },
  {
    name: "Cartier Tank Solo",
    original_price: 50000,
    discounted: 45000,
    price: 45000,
    case_size: ["41 - 43mm", "44 - 46mm"],
    availability: "Available",
    gender: "Men",
    brands: "Hublot",
    buy_back_assurance: "80%",
    dial_colours: ["Black"],
    watch_styles: ["Sport"],
    strap_bracelet_material: "Steel",
    strap_colours: ["Black"],
    movement_type: "Automatic",
    case_material: "Rose Gold",
    purchase_year: "2015",
    liked: true,
    relevance: 8,
    best_seller: 7,
    new_arrival: 3,
    editor_top_picks: 10,
  },
  {
    name: "Armani Exchange Women's Dress Watch",
    original_price: 25000,
    discounted: 22000,
    price: 22000,
    case_size: ["35 - 37mm", "38 - 40mm"],
    availability: "Available",
    gender: "Unisex",
    brands: "Cartier",
    buy_back_assurance: "60%",
    dial_colours: ["Brown", "Red"],
    watch_styles: ["Casual", "Aviator"],
    strap_bracelet_material: "Leather",
    strap_colours: ["Brown", "Burgundy"],
    movement_type: "Quartz",
    case_material: "Yellow Gold",
    purchase_year: "2013",
    liked: true,
    relevance: 6,
    best_seller: 4,
    new_arrival: 8,
    editor_top_picks: 2,
  },
  {
    name: "Guess Men's Sport Watch",
    original_price: 200,
    discounted: 150,
    price: 150,
    case_size: ["17 - 19mm", "20 - 22mm"],
    availability: "Available",
    gender: "Men",
    brands: "Rolex",
    buy_back_assurance: "80%",
    dial_colours: ["Black", "Brown"],
    watch_styles: ["Vintage", "Sport"],
    strap_bracelet_material: "Leather",
    strap_colours: ["Black", "Brown"],
    movement_type: "Automatic",
    case_material: "Stainless Steel",
    purchase_year: "2012",
    liked: true,
    relevance: 5,
    best_seller: 6,
    new_arrival: 5,
    editor_top_picks: 9,
  },
  {
    name: "Chanel J12 Ceramic Watch",
    original_price: 300,
    discounted: 250,
    price: 250,
    case_size: ["23 - 25mm", "26 - 28mm"],
    availability: "Available",
    gender: "Women",
    brands: "Apple",
    buy_back_assurance: "60%",
    dial_colours: ["Burgundy", "Red"],
    watch_styles: ["Dress", "Casual"],
    strap_bracelet_material: "Steel",
    strap_colours: ["Black", "Blue"],
    movement_type: "Quartz",
    case_material: "Silver",
    purchase_year: "2014",
    liked: false,
    relevance: 7,
    best_seller: 2,
    new_arrival: 5,
    editor_top_picks: 6,
  },
  {
    name: "Hublot Classic Fusion",
    original_price: 1500,
    discounted: 1200,
    price: 1200,
    case_size: ["32 - 34mm", "35 - 37mm"],
    availability: "Sold",
    gender: "Unisex",
    brands: "Aspen",
    buy_back_assurance: "80%",
    dial_colours: ["Blue"],
    watch_styles: ["Diver"],
    strap_bracelet_material: "Rubber",
    strap_colours: ["Purple"],
    movement_type: "Manual",
    case_material: "Stainless Steel and Gold",
    purchase_year: "2016",
    liked: false,
    relevance: 3,
    best_seller: 9,
    new_arrival: 7,
    editor_top_picks: 3,
  },
  {
    name: "Cartier Santos de Cartier",
    original_price: 50000,
    discounted: 45000,
    price: 45000,
    case_size: ["41 - 43mm", "44 - 46mm"],
    availability: "Available",
    gender: "Men",
    brands: "Hublot",
    buy_back_assurance: "80%",
    dial_colours: ["Black"],
    watch_styles: ["Sport"],
    strap_bracelet_material: "Steel",
    strap_colours: ["Black"],
    movement_type: "Automatic",
    case_material: "Rose Gold",
    purchase_year: "2015",
    liked: true,
    relevance: 8,
    best_seller: 8,
    new_arrival: 10,
    editor_top_picks: 1,
  },
  {
    name: "TAG Heuer Carrera",
    original_price: 25000,
    discounted: 22000,
    price: 22000,
    case_size: ["35 - 37mm", "38 - 40mm"],
    availability: "Available",
    gender: "Unisex",
    brands: "Cartier",
    buy_back_assurance: "60%",
    dial_colours: ["Brown", "Red"],
    watch_styles: ["Casual", "Aviator"],
    strap_bracelet_material: "Leather",
    strap_colours: ["Brown", "Burgundy"],
    movement_type: "Quartz",
    case_material: "Yellow Gold",
    purchase_year: "2013",
    liked: true,
    relevance: 6,
    best_seller: 4,
    new_arrival: 3,
    editor_top_picks: 6,
  },
  {
    name: "Omega Seamaster",
    original_price: 150,
    discounted: 120,
    price: 120,
    case_size: ["17 - 19mm"],
    availability: "Available",
    gender: "Women",
    brands: "Armani Exchange",
    buy_back_assurance: "80%",
    dial_colours: ["Black"],
    watch_styles: ["Casual"],
    strap_bracelet_material: "Fabric",
    strap_colours: ["Blue"],
    movement_type: "Quartz",
    case_material: "Stainless Steel",
    purchase_year: "2014",
    liked: false,
    relevance: 4,
    best_seller: 1,
    new_arrival: 2,
    editor_top_picks: 5,
  },
  {
    name: "Tissot Le Locle",
    original_price: 8000,
    discounted: 7000,
    price: 7000,
    case_size: ["26 - 28mm"],
    availability: "Sold",
    gender: "Women",
    brands: "Chanel",
    buy_back_assurance: "60%",
    dial_colours: ["Burgundy"],
    watch_styles: ["Dress"],
    strap_bracelet_material: "Leather",
    strap_colours: ["Red"],
    movement_type: "Quartz",
    case_material: "Stainless Steel and Gold",
    purchase_year: "2016",
    liked: true,
    relevance: 7,
    best_seller: 7,
    new_arrival: 6,
    editor_top_picks: 8,
  },
  {
    name: "Breitling Navitimer",
    original_price: 60000,
    discounted: 55000,
    price: 55000,
    case_size: ["29 - 31mm"],
    availability: "Available",
    gender: "Men",
    brands: "Ball",
    buy_back_assurance: "80%",
    dial_colours: ["Brown"],
    watch_styles: ["Vintage"],
    strap_bracelet_material: "Leather",
    strap_colours: ["Black"],
    movement_type: "Automatic",
    case_material: "Stainless Steel",
    purchase_year: "2015",
    liked: false,
    relevance: 3,
    best_seller: 10,
    new_arrival: 9,
    editor_top_picks: 4,
  },
  {
    name: "Patek Philippe Nautilus",
    original_price: 35000,
    discounted: 30000,
    price: 30000,
    case_size: ["32 - 34mm"],
    availability: "Available",
    gender: "Women",
    brands: "Guess",
    buy_back_assurance: "60%",
    dial_colours: ["Black", "Blue"],
    watch_styles: ["Sport", "Casual"],
    strap_bracelet_material: "Rubber",
    strap_colours: ["Purple"],
    movement_type: "Quartz",
    case_material: "Silver",
    purchase_year: "2013",
    liked: true,
    relevance: 9,
    best_seller: 3,
    new_arrival: 5,
    editor_top_picks: 2,
  },
  {
    name: "Seiko Prospex",
    original_price: 120000,
    discounted: 100000,
    price: 100000,
    case_size: ["41 - 43mm"],
    availability: "Sold",
    gender: "Men",
    brands: "Hugo Boss",
    buy_back_assurance: "80%",
    dial_colours: ["Blue"],
    watch_styles: ["Diver"],
    strap_bracelet_material: "Steel",
    strap_colours: ["Black"],
    movement_type: "Automatic",
    case_material: "Rose Gold",
    purchase_year: "2016",
    liked: false,
    relevance: 6,
    best_seller: 6,
    new_arrival: 1,
    editor_top_picks: 10,
  },
  {
    name: "Citizen Eco-Drive",
    original_price: 10000,
    discounted: 9000,
    price: 9000,
    case_size: ["20 - 22mm"],
    availability: "Available",
    gender: "Men",
    brands: "Rolex",
    buy_back_assurance: "80%",
    dial_colours: ["Black", "Brown"],
    watch_styles: ["Vintage", "Sport"],
    strap_bracelet_material: "Leather",
    strap_colours: ["Black", "Brown"],
    movement_type: "Automatic",
    case_material: "Stainless Steel",
    purchase_year: "2014",
    liked: true,
    relevance: 5,
    best_seller: 8,
    new_arrival: 9,
    editor_top_picks: 7,
  },
  {
    name: "Bulova Precisionist",
    original_price: 20000,
    discounted: 18000,
    price: 18000,
    case_size: ["23 - 25mm"],
    availability: "Available",
    gender: "Women",
    brands: "Apple",
    buy_back_assurance: "60%",
    dial_colours: ["Burgundy", "Red"],
    watch_styles: ["Dress", "Casual"],
    strap_bracelet_material: "Steel",
    strap_colours: ["Black", "Blue"],
    movement_type: "Quartz",
    case_material: "Silver",
    purchase_year: "2015",
    liked: false,
    relevance: 7,
    best_seller: 4,
    new_arrival: 2,
    editor_top_picks: 1,
  },
  {
    name: "Fossil Grant Chronograph",
    original_price: 5000,
    discounted: 4000,
    price: 4000,
    case_size: ["29 - 31mm"],
    availability: "Sold",
    gender: "Unisex",
    brands: "Aspen",
    buy_back_assurance: "80%",
    dial_colours: ["Blue"],
    watch_styles: ["Diver"],
    strap_bracelet_material: "Rubber",
    strap_colours: ["Purple"],
    movement_type: "Manual",
    case_material: "Stainless Steel and Gold",
    purchase_year: "2012",
    liked: false,
    relevance: 3,
    best_seller: 3,
    new_arrival: 10,
    editor_top_picks: 5,
  },
  {
    name: "Hamilton Khaki Field",
    original_price: 45000,
    discounted: 40000,
    price: 40000,
    case_size: ["44 - 46mm"],
    availability: "Available",
    gender: "Men",
    brands: "Hublot",
    buy_back_assurance: "80%",
    dial_colours: ["Black"],
    watch_styles: ["Sport"],
    strap_bracelet_material: "Steel",
    strap_colours: ["Black"],
    movement_type: "Automatic",
    case_material: "Rose Gold",
    purchase_year: "2013",
    liked: true,
    relevance: 8,
    best_seller: 6,
    new_arrival: 7,
    editor_top_picks: 4,
  },
  {
    name: "Longines Master Collection",
    original_price: 22000,
    discounted: 20000,
    price: 20000,
    case_size: ["35 - 37mm"],
    availability: "Available",
    gender: "Unisex",
    brands: "Cartier",
    buy_back_assurance: "60%",
    dial_colours: ["Brown", "Red"],
    watch_styles: ["Casual", "Aviator"],
    strap_bracelet_material: "Leather",
    strap_colours: ["Brown", "Burgundy"],
    movement_type: "Quartz",
    case_material: "Yellow Gold",
    purchase_year: "2014",
    liked: true,
    relevance: 6,
    best_seller: 1,
    new_arrival: 8,
    editor_top_picks: 9,
  },
  {
    name: "Movado Museum Classic",
    original_price: 120,
    discounted: 100,
    price: 100,
    case_size: ["17 - 19mm"],
    availability: "Available",
    gender: "Women",
    brands: "Armani Exchange",
    buy_back_assurance: "80%",
    dial_colours: ["Black"],
    watch_styles: ["Casual"],
    strap_bracelet_material: "Fabric",
    strap_colours: ["Blue"],
    movement_type: "Quartz",
    case_material: "Stainless Steel",
    purchase_year: "2016",
    liked: false,
    relevance: 4,
    best_seller: 5,
    new_arrival: 3,
    editor_top_picks: 2,
  },
  {
    name: "Rado HyperChrome",
    original_price: 7000,
    discounted: 6000,
    price: 6000,
    case_size: ["26 - 28mm"],
    availability: "Sold",
    gender: "Women",
    brands: "Chanel",
    buy_back_assurance: "60%",
    dial_colours: ["Burgundy"],
    watch_styles: ["Dress"],
    strap_bracelet_material: "Leather",
    strap_colours: ["Red"],
    movement_type: "Quartz",
    case_material: "Stainless Steel and Gold",
    purchase_year: "2015",
    liked: true,
    relevance: 7,
    best_seller: 9,
    new_arrival: 6,
    editor_top_picks: 10,
  },
  {
    name: "Swatch Sistem51",
    original_price: 55000,
    discounted: 50000,
    price: 50000,
    case_size: ["29 - 31mm"],
    availability: "Available",
    gender: "Men",
    brands: "Ball",
    buy_back_assurance: "80%",
    dial_colours: ["Brown"],
    watch_styles: ["Vintage"],
    strap_bracelet_material: "Leather",
    strap_colours: ["Black"],
    movement_type: "Automatic",
    case_material: "Stainless Steel",
    purchase_year: "2013",
    liked: false,
    relevance: 3,
    best_seller: 7,
    new_arrival: 1,
    editor_top_picks: 8,
  },
  {
    name: "Timex Weekender",
    original_price: 30000,
    discounted: 25000,
    price: 25000,
    case_size: ["32 - 34mm"],
    availability: "Available",
    gender: "Women",
    brands: "Guess",
    buy_back_assurance: "60%",
    dial_colours: ["Black", "Blue"],
    watch_styles: ["Sport", "Casual"],
    strap_bracelet_material: "Rubber",
    strap_colours: ["Purple"],
    movement_type: "Quartz",
    case_material: "Silver",
    purchase_year: "2014",
    liked: true,
    relevance: 9,
    best_seller: 10,
    new_arrival: 4,
    editor_top_picks: 3,
  },
  {
    name: "Vacheron Constantin Patrimony",
    original_price: 100000,
    discounted: 90000,
    price: 90000,
    case_size: ["41 - 43mm"],
    availability: "Sold",
    gender: "Men",
    brands: "Hugo Boss",
    buy_back_assurance: "80%",
    dial_colours: ["Blue"],
    watch_styles: ["Diver"],
    strap_bracelet_material: "Steel",
    strap_colours: ["Black"],
    movement_type: "Automatic",
    case_material: "Rose Gold",
    purchase_year: "2015",
    liked: false,
    relevance: 6,
    best_seller: 2,
    new_arrival: 5,
    editor_top_picks: 9,
  },
];
